# Import all packages

In [5]:
import numpy as np

# Loading Data-Set

In [6]:
X = np.random.random((10,5))
#shape of X
print(X.shape)
print(X)

(10, 5)
[[0.17603924 0.92684366 0.92386353 0.49615542 0.92493081]
 [0.34874157 0.95518219 0.39220512 0.40611652 0.21716851]
 [0.9886039  0.81123116 0.3189177  0.8811493  0.6632707 ]
 [0.92763596 0.17607881 0.62152886 0.57603278 0.79719401]
 [0.13362162 0.27075611 0.5174881  0.32209362 0.08562786]
 [0.08767142 0.91616159 0.61496624 0.4041648  0.82281408]
 [0.1701207  0.01815061 0.00535725 0.27652105 0.88893811]
 [0.28773553 0.14427026 0.13870256 0.52502234 0.98740154]
 [0.37755163 0.7680914  0.52318521 0.49953189 0.70180903]
 [0.70585835 0.29313408 0.07608361 0.52046117 0.25885263]]


In [7]:
y = np.array(['M','F','M','M','M','F','M','F','M','F'])
#shape of y
print(y.shape)
y

(10,)


array(['M', 'F', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'F'], dtype='<U1')

In [8]:
#for simplified X(feature-set)
X[X < 0.7] = 0
X

array([[0.        , 0.92684366, 0.92386353, 0.        , 0.92493081],
       [0.        , 0.95518219, 0.        , 0.        , 0.        ],
       [0.9886039 , 0.81123116, 0.        , 0.8811493 , 0.        ],
       [0.92763596, 0.        , 0.        , 0.        , 0.79719401],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.91616159, 0.        , 0.        , 0.82281408],
       [0.        , 0.        , 0.        , 0.        , 0.88893811],
       [0.        , 0.        , 0.        , 0.        , 0.98740154],
       [0.        , 0.7680914 , 0.        , 0.        , 0.70180903],
       [0.70585835, 0.        , 0.        , 0.        , 0.        ]])

# Split Data-Set into Train Set And Test Set

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0) 

# initialize Models

In [11]:
#support vector machines(svm)
from sklearn.svm import SVC
svc = SVC(kernel='linear')

In [12]:
#KNN
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier(n_neighbors=4)

In [13]:
#Naive Bayes 
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [14]:
# Principal Component Analysis(PCA) 
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)

In [15]:
# K-Means 
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=4, random_state=0)

# Fit Data Into Models

In [16]:
svc.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=4, p=2,
           weights='uniform')

In [18]:
gnb.fit(X_train, y_train)

GaussianNB(priors=None)

In [19]:
k_means.fit(X_train)


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=4, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [20]:
pca_model = pca.fit_transform(X_train)


# Prediction

In [95]:
pred = svc.predict(X_test)
print(pred)

['F' 'F' 'F']


In [96]:
pred = knn.predict(X_test)
print(pred)

['F' 'F' 'F']


In [97]:
pred = gnb.predict(X_test)
print(pred)

['F' 'F' 'F']


In [21]:
pred = k_means.predict(X_test)
pred

array([0, 1, 0], dtype=int32)